---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/geocode/forward":
    get:
      summary: Gets lat and lon for location string
      security:
      - basic: []
      tags:
      - Geocoding
      parameters:
      - name: query
        in: query
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  lat:
                    type: string
                  lon:
                    type: string
                  place_id:
                    type: string
                  osm_type:
                    type: string
                  osm_id:
                    type: string
                  display_name:
                    type: string
                  class:
                    type: string
                  type:
                    type: string
                  importance:
                    type: number
                  icon:
                    type: string
                  status:
                    type: integer
                  permanent_api_endpoint_location:
                    type: string
        '400':
          description: must provide a query
        '401':
          description: must pass basic auth
